### ISSUE TITLE
Fails to Install on Alpine Linux (Docker)

### ISSUE THREAD

**Issue by coreybutler** [electron/node-minidump#15]
I'm attempting to install this on Alpine Linux (the soon-to-be standard OS for Docker Images). Alpine is pretty bare, so I'm hoping this is just a missing dependency, but I can get other native modules to compile (like bcrypt). The standard libs I've installed on the base Alpine image include `make`, `gcc`, `g++`, and `python`, and it's running Node 4.4.3 at the moment.

The log looks like:

``` sh
/app # npm i minidump
> minidump@0.9.0 install /app/node_modules/minidump
> node-gyp rebuild

make: Entering directory '/app/node_modules/minidump/build'
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf/bytereader.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf_cfi_to_module.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf_cu_to_module.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf/dwarf2diehandler.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf/dwarf2reader.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf_line_to_module.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/language.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/linux/crc32.o
  CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/linux/dump_symbols.o
In file included from ../deps/breakpad/src/common/linux/dump_symbols.cc:69:0:
../deps/breakpad/src/common/stabs_reader.h:57:19: fatal error: a.out.h: No such file or directory
compilation terminated.
deps/breakpad/dump_syms.target.mk:109: recipe for target 'Release/obj.target/dump_syms/deps/breakpad/src/common/linux/dump_symbols.o' failed
make: *** [Release/obj.target/dump_syms/deps/breakpad/src/common/linux/dump_symbols.o] Error 1
make: Leaving directory '/app/node_modules/minidump/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.6
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/minidump
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 4.4.6
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "minidump"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.3
npm ERR! code ELIFECYCLE

npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the minidump@0.9.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs minidump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.
An error occurred trying to connect: EOF
```

**Comment by Skarlso** [comment]
Me too. Were you able to figure this out @coreybutler?

**Comment by coreybutler** [comment]
@Skarlso - No, I still haven't got this working.

**Comment by Skarlso** [comment]
@coreybutler I've got further with this after I installed a bunch of linux-header libraries. Then a.out.h showed up in /usr/include/linux. Doing that, I created a symlink to that file with: 
```
   cd /usr/include 
   ln -s linux/a.out.h . 
```

However, now I'm facing this: 
```
./deps/breakpad/src/common/linux/dump_symbols.cc:798:36: error: 'basename' was not declared in this scope
```

I tracked it down to this part of the code:
https://chromium.googlesource.com/external/google-breakpad/+/master/src/common/linux/dump_symbols.cc#849

And that's it. I'm stuck here.

**Comment by coreybutler** [comment]
This seems vaguely familiar to me. Now that you mention it, I remember trying to symlink to that file as well, but I never tracked it down the way you did. The line that concerns me is 

https://chromium.googlesource.com/external/google-breakpad/+/master/src/common/linux/dump_symbols.cc#847

I'm currently working on another aspect of my project and will likely look into this more... but that's probably a few weeks from now. If you come up with anything in the meantime, I'd love to hear about it... and maybe we can get someone from the atom team to provide some guidance.

@zcbenz - is this something you could provide some guidance on (or point us to someone who can)?

**Comment by Skarlso** [comment]
Sure I'll tell ya. 

That basename is part of something called libgen which is there on alpine, but is not referenced by that Google stuff so it's really weird. I think we are better off if we just remove minidump and replace it with the stiff that's suggested by node-gsp anyways. :-)

**Comment by Skarlso** [comment]
@coreybutler Very quick workaround if you don't care about processing dump files for Darwin based architecture:

Remove the following line build/package.json:
```
    "minidump": "~0.9",
```

Remove the following task:
```
dump-symbols-task.coffee
```

Remove the following ciTasks.push from Gruntfile.coffee:
```
ciTasks.push('dump-symbols') if process.platform is 'darwin'
```

After this, I've got a gnome-key error but that was easily solved by ```apk add gnome-keyring``` and ```apk add libgnome-keyring-dev```. Both are heavy packages unfortunately.

Cheers,
Gergely.
