### ISSUE TITLE
walkStack from buffer

### ISSUE THREAD

**Issue by acrisci** [electron/node-minidump#24]
Hi,

I would like to walk the stack of a minidump file from a database and not from the file system because that's how I'm storing them. I get it from the database in the form of a node byte buffer.

What I want is sort of like this.

    minidump.walkStack(buffer, [symbolPaths, ]callback)

Do you think that would be possible?

Thanks.

**Comment by yoshuawuyts** [comment]
This would be very beneficial. I'm currently [working on a service to handle electron crash reports](https://github.com/yoshuawuyts/electron-crash-report-service) and having the minidump parser coupled to IO has been a tad unwieldy

**Comment by yoshuawuyts** [comment]
Ah yeah, after digging some more [it appears Breakpad only runs on files](https://chromium.googlesource.com/breakpad/breakpad/+/master/docs/linux_starter_guide.md) - my C++ isn't that far out but yeah, it'd explain why this wrapper also only operates on files.

Might end up wrapping a buffer-to-tmpfs layer for this
