### ISSUE TITLE
won't install on freebsd 10

### ISSUE THREAD

**Issue by abiliojr** [electron/node-minidump#4]
The package won't install on freebsd 10, it gives:

gyp: Dependency 'deps/breakpad/breakpad.gyp:dump_syms#target' not found while trying to load target binding.gyp:minidump#target
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System FreeBSD 10.0-RELEASE
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/amarques/tmp/atom/build/node_modules/minidump
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm ERR! minidump@0.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1

**Comment by tony** [comment]
Same on 11-CURRENT

```
❯ freebsd-version -ku; uname -apKU        
11.0-CURRENT
11.0-CURRENT
FreeBSD z600 11.0-CURRENT FreeBSD 11.0-CURRENT #42: Mon Jan 11 21:09:38 CST 2016     root@z600:/usr/obj/usr/src/sys/MYKERNEL  amd64 amd64 1100093 1100093
```

```
❯ script/build             
Node: v5.2.0
npm: v2.13.3
Installing build modules...
Traceback (most recent call last):
  File "/usr/home/tony/study/node/atom/build/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/home/tony/study/node/atom/build/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "/usr/home/tony/study/node/atom/build/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 526, in main
    return gyp_main(args)
  File "/usr/home/tony/study/node/atom/build/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 502, in gyp_main
    params, options.check, options.circular_check)
  File "/usr/home/tony/study/node/atom/build/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/usr/home/tony/study/node/atom/build/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2756, in Load
    RemoveLinkDependenciesFromNoneTargets(targets)
  File "/usr/home/tony/study/node/atom/build/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1501, in RemoveLinkDependenciesFromNoneTargets
    if targets[t].get('variables', {}).get('link_dependency', 0):
KeyError: 'deps/breakpad/breakpad.gyp:dump_syms#target'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/home/tony/study/node/atom/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
gyp ERR! System FreeBSD 11.0-CURRENT
gyp ERR! command "/usr/local/bin/node" "/usr/home/tony/study/node/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/tony/study/node/atom/build/node_modules/minidump
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! FreeBSD 11.0-CURRENT
npm ERR! argv "/usr/local/bin/node" "/usr/home/tony/study/node/atom/build/node_modules/.bin/npm" "--userconfig=/usr/home/tony/study/node/atom/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v5.2.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minidump@0.9.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/tony/study/node/atom/build/npm-debug.log
```

**Comment by Makdiuk** [comment]
Some Progress ?

**Comment by kulinp** [comment]
Same problem here on FreeBSD (10.3) when attempting to build the atom editor.
Node version 6.1.0
npm version 3.8.9
minidump version 0.9.0

`$ script/build 
Node: v6.1.0  
npm: v3.8.9  
Installing build modules...
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2795, in Load
    RemoveLinkDependenciesFromNoneTargets(targets)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1510, in RemoveLinkDependenciesFromNoneTargets
    if targets[t].get('variables', {}).get('link_dependency', 0):
KeyError: 'deps/breakpad/breakpad.gyp:dump_syms#target'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System FreeBSD 10.3-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/kulin/workspace/atom/build/node_modules/minidump
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! FreeBSD 10.3-RELEASE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--userconfig=/usr/home/kulin/workspace/atom/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minidump@0.9.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs minidump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.
`

**Comment by kirked** [comment]
Still failing on `System FreeBSD 11.0-BETA4` (x64), building Atom.
Node: 6.3.1
NPM: 3.10.5

**Comment by sturmer** [comment]
I confirm the problem with FreeBSD 10.3-RELEASE-p7, node v6.2.2, and npm 3.9.2.
[npm-debug.log.txt](https://github.com/atom/node-minidump/files/418125/npm-debug.log.txt)

**Comment by galeido** [comment]
I have exactly same issue with FreeBSD 11

Node:   v6.8.0
Npm:    v3.10.5

**Comment by pizzamig** [comment]
I have successfully built minidump on FreeBSD, removing some lines in binding.gyp
Surprisingly, it looks like freebsd is recognized as windows, and the build scripts fails to build dump_syms.
This patch would break  windows support, so it's not acceptable, but it shows how to get things done on FreeBSD.

```
diff --git a/binding.gyp b/binding.gyp
index dc655b3..e69d367 100644
--- a/binding.gyp
+++ b/binding.gyp
@@ -3,15 +3,6 @@
     {
       'target_name': 'minidump',
       'type': 'none',
-      'conditions': [
-        ['OS=="win"', {
-        }, {
-          'dependencies': [
-            'deps/breakpad/breakpad.gyp:minidump_stackwalk',
-            'deps/breakpad/breakpad.gyp:dump_syms#host',
-          ],
-        }],
-      ],
     }
   ]
 }
```
