### ISSUE TITLE
minidump.js commands execute error

### ISSUE THREAD

**Issue by weiweian90** [electron/node-minidump#44]
minidump version 0.19.0
I install minidump by npm intall minidump@0.19.0 --no-bin-links
but node_modules/minidump/build have nothing, the minidump.js content commands excute path minidump\build\src\processor\minidump_stackwalk.exe is not exsit

**Comment by nornagon** [comment]
sounds like an npm issue. what OS are you on? if you install without `--no-bin-links` does it work?

**Comment by nornagon** [comment]
Ah, okay, well sadly that is beyond my control to fix :/
