### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by aminya** [electron/node-minidump#46]
It's been two years since the previous release and the pull requests are merged without releasing a new version. Could you release a new version on NPM?

The tutorial for releasing is here:
https://github.com/electron/node-minidump#releasing-a-new-npm-version

**Comment by aminya** [comment]
@nornagon Would you be able to release a new version?

The tutorial for releasing is here:
electron/node-minidump#releasing-a-new-npm-version

**Comment by jkleinsc** [comment]
v0.22.0 has been released with the latest updates.
