### ISSUE TITLE
Windows 11 installation failure

### ISSUE THREAD

**Issue by cx-github** [electron/node-minidump#62]
$ npm install minidump

npm ERR! code 1
npm ERR! path D:\dount\node_modules\minidump
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node build.js
npm ERR! D:\dount\node_modules\minidump\build.js:24
npm ERR!   if (result.error) throw result.error
npm ERR!                     ^
npm ERR!
npm ERR! Error: spawnSync D:\dount\node_modules\minidump\deps\breakpad\configure ENOENT
npm ERR!     at Object.spawnSync (node:internal/child_process:1110:20)
npm ERR!     at Object.spawnSync (node:child_process:871:24)
npm ERR!     at spawnSync (D:\dount\node_modules\minidump\build.js:23:31)
npm ERR!     at Object.<anonymous> (D:\dount\node_modules\minidump\build.js:42:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:958:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:23:47 {
npm ERR!   errno: -4058,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'spawnSync D:\\dount\\node_modules\\minidump\\deps\\breakpad\\configure',
npm ERR!   path: 'D:\\dount\\node_modules\\minidump\\deps\\breakpad\\configure',
npm ERR!   spawnargs: []
npm ERR! }
npm ERR!
npm ERR! Node.js v18.16.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Local\npm-cache\_logs\2023-07-06T07_04_56_577Z-debug-0.log

**Comment by dogeFu** [comment]
Having the same problem, is there an additional tool or environment variable setting required on Windows? breakpad/configure is not a recognizable script! @codebytere
